name: Build and deploy a container image to Azure Web Apps

on:
  push:
    branches:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@main

    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with:
        app-name: prod-agh-event-hub-api
        resource-group-name: prod-rg
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}
        images: "docker.io/enriquecatala/fastapi-helloworld:2022-02-09"
